/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2.s.p0041.drawshape;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;

/**
 *
 * @author Nhat Thanh
 */
public class DrawShape extends javax.swing.JFrame {

    /**
     * Creates new form DrawShape
     */
    public DrawShape() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBackGround = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnRect = new javax.swing.JMenuItem();
        mnOval = new javax.swing.JMenuItem();
        mnRRect = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Red = new javax.swing.JRadioButtonMenuItem();
        Green = new javax.swing.JRadioButtonMenuItem();
        Blue = new javax.swing.JRadioButtonMenuItem();
        Cyan = new javax.swing.JRadioButtonMenuItem();
        Magenta = new javax.swing.JRadioButtonMenuItem();
        Yellow = new javax.swing.JRadioButtonMenuItem();
        Black = new javax.swing.JRadioButtonMenuItem();
        White = new javax.swing.JRadioButtonMenuItem();
        Gray = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnClear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnAddLS = new javax.swing.JCheckBoxMenuItem();
        mnAddSwB = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnBackGround = new javax.swing.JMenu();
        Bred = new javax.swing.JMenuItem();
        Bgreen = new javax.swing.JMenuItem();
        Bblue = new javax.swing.JMenuItem();
        Bcyan = new javax.swing.JMenuItem();
        Bmagenta = new javax.swing.JMenuItem();
        Byellow = new javax.swing.JMenuItem();
        Bblack = new javax.swing.JMenuItem();
        Bwhite = new javax.swing.JMenuItem();
        Bgray = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Draw Shape");

        javax.swing.GroupLayout pnlBackGroundLayout = new javax.swing.GroupLayout(pnlBackGround);
        pnlBackGround.setLayout(pnlBackGroundLayout);
        pnlBackGroundLayout.setHorizontalGroup(
            pnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        pnlBackGroundLayout.setVerticalGroup(
            pnlBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        jMenu1.setMnemonic('A');
        jMenu1.setText("Add");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        mnRect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnRect.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mnRect.setText("Rectangle");
        mnRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRectActionPerformed(evt);
            }
        });
        jMenu1.add(mnRect);

        mnOval.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnOval.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mnOval.setText("Oval");
        mnOval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOvalActionPerformed(evt);
            }
        });
        jMenu1.add(mnOval);

        mnRRect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnRRect.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mnRRect.setText("Round Retangle");
        mnRRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRRectActionPerformed(evt);
            }
        });
        jMenu1.add(mnRRect);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('c');
        jMenu2.setText("Color");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        buttonGroup1.add(Red);
        Red.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Red.setText("Red");
        jMenu2.add(Red);

        buttonGroup1.add(Green);
        Green.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Green.setText("Green");
        jMenu2.add(Green);

        buttonGroup1.add(Blue);
        Blue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Blue.setText("Blue");
        jMenu2.add(Blue);

        buttonGroup1.add(Cyan);
        Cyan.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Cyan.setText("Cyan");
        jMenu2.add(Cyan);

        buttonGroup1.add(Magenta);
        Magenta.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Magenta.setText("Magenta");
        jMenu2.add(Magenta);

        buttonGroup1.add(Yellow);
        Yellow.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Yellow.setText("Yellow");
        jMenu2.add(Yellow);

        buttonGroup1.add(Black);
        Black.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Black.setText("Black");
        jMenu2.add(Black);

        buttonGroup1.add(White);
        White.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        White.setText("White");
        jMenu2.add(White);

        buttonGroup1.add(Gray);
        Gray.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Gray.setText("Gray");
        jMenu2.add(Gray);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('O');
        jMenu3.setText("Options");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        mnClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnClear.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mnClear.setText("Clear");
        mnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClearActionPerformed(evt);
            }
        });
        jMenu3.add(mnClear);
        jMenu3.add(jSeparator1);

        mnAddLS.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mnAddLS.setText("Add Large Shapes");
        jMenu3.add(mnAddLS);

        mnAddSwB.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        mnAddSwB.setText("Add Shapes with Border");
        jMenu3.add(mnAddSwB);
        jMenu3.add(jSeparator2);

        mnBackGround.setText("Background Color");
        mnBackGround.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        Bred.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bred.setText("Red");
        Bred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BredActionPerformed(evt);
            }
        });
        mnBackGround.add(Bred);

        Bgreen.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bgreen.setText("Green");
        Bgreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgreenActionPerformed(evt);
            }
        });
        mnBackGround.add(Bgreen);

        Bblue.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bblue.setText("Blue");
        Bblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BblueActionPerformed(evt);
            }
        });
        mnBackGround.add(Bblue);

        Bcyan.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bcyan.setText("Cyan");
        Bcyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcyanActionPerformed(evt);
            }
        });
        mnBackGround.add(Bcyan);

        Bmagenta.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bmagenta.setText("Magenta");
        Bmagenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmagentaActionPerformed(evt);
            }
        });
        mnBackGround.add(Bmagenta);

        Byellow.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Byellow.setText("Yellow");
        Byellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByellowActionPerformed(evt);
            }
        });
        mnBackGround.add(Byellow);

        Bblack.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bblack.setText("Black");
        Bblack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BblackActionPerformed(evt);
            }
        });
        mnBackGround.add(Bblack);

        Bwhite.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bwhite.setText("White");
        Bwhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BwhiteActionPerformed(evt);
            }
        });
        mnBackGround.add(Bwhite);

        Bgray.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Bgray.setText("Gray");
        Bgray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgrayActionPerformed(evt);
            }
        });
        mnBackGround.add(Bgray);

        jMenu3.add(mnBackGround);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnOvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOvalActionPerformed
        // TODO add your handling code here:
        int x = 200,y = 100;
        if (mnAddLS.isSelected()){
            x *= 2;
            y *= 2;
        }
        paintOval(pnlBackGround.getGraphics(), x, y);
    }//GEN-LAST:event_mnOvalActionPerformed

    private void mnRRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRRectActionPerformed
        // TODO add your handling code here:
        int x = 200,y = 100;
        if (mnAddLS.isSelected()){
            x *= 2;
            y *= 2;
        }
        paintRR(pnlBackGround.getGraphics(), x, y);
    }//GEN-LAST:event_mnRRectActionPerformed

    private void mnRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRectActionPerformed
        // TODO add your handling code here:
        int x = 200,y = 100;
        if (mnAddLS.isSelected()){
            x *= 2;
            y *= 2;
        }
        paintRectt(pnlBackGround.getGraphics(), x, y);
    }//GEN-LAST:event_mnRectActionPerformed

    private void mnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClearActionPerformed
        // TODO add your handling code here:
        pnlBackGround.repaint();
    }//GEN-LAST:event_mnClearActionPerformed

    private void BredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BredActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.RED);
    }//GEN-LAST:event_BredActionPerformed

    private void BblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BblueActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.BLUE);
    }//GEN-LAST:event_BblueActionPerformed

    private void BgreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgreenActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.GREEN);
    }//GEN-LAST:event_BgreenActionPerformed

    private void BcyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcyanActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.CYAN);
    }//GEN-LAST:event_BcyanActionPerformed

    private void BmagentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmagentaActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_BmagentaActionPerformed

    private void ByellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByellowActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.YELLOW);
    }//GEN-LAST:event_ByellowActionPerformed

    private void BblackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BblackActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.BLACK);
    }//GEN-LAST:event_BblackActionPerformed

    private void BwhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BwhiteActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.WHITE);
    }//GEN-LAST:event_BwhiteActionPerformed

    private void BgrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgrayActionPerformed
        // TODO add your handling code here:
        pnlBackGround.setBackground(Color.GRAY);
    }//GEN-LAST:event_BgrayActionPerformed
    public int random(int num){
        Random rand = new Random();
        int n = rand.nextInt(num);
        return n;   
    }
    public Color gtColor(){
        if (Red.isSelected()){
            return Color.RED;
        } else if (Green.isSelected()){
            return Color.GREEN;
        } else if (Blue.isSelected()){
            return Color.BLUE;
        } else if (Cyan.isSelected()){
            return Color.CYAN;
        } else if (Yellow.isSelected()){
            return Color.YELLOW;
        } else if (Gray.isSelected()){
            return Color.GRAY;
        } else if (White.isSelected()){
            return Color.WHITE;
        } else if (Black.isSelected()){
            return Color.BLACK;
        } 
        if (Magenta.isSelected()){
            return Color.MAGENTA;
        }
        return null;
    }
    public void paintRectt(Graphics g, int x, int y){
        int ran1 = random(pnlBackGround.getWidth());
        int ran2 = random(pnlBackGround.getHeight());
        g.setColor(gtColor());
        g.fillRect(ran1, ran2, x, y);
        if (mnAddSwB.isSelected()){
            g.setColor(Color.BLACK);
            g.fillRect(ran1, ran2, x, y);
        }
    }
    public void paintOval(Graphics g, int x, int y){
        int ran1 = random(pnlBackGround.getWidth());
        int ran2 = random(pnlBackGround.getHeight());
        g.setColor(gtColor());
        g.fillOval(ran1, ran2, x, y);
        if (mnAddSwB.isSelected()){
            g.setColor(Color.BLACK);
            g.fillOval(ran1, ran2, x, y);
        }
    }
    public void paintRR(Graphics g, int x, int y){
        int ran1 = random(pnlBackGround.getWidth());
        int ran2 = random(pnlBackGround.getHeight());
        g.setColor(gtColor());
        g.fillRoundRect(ran1, ran2, x, y, 50, 50);
        if (mnAddSwB.isSelected()){
            g.setColor(Color.BLACK);
            g.fillRoundRect(ran1, ran2, x, y, 50, 50);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawShape().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Bblack;
    private javax.swing.JMenuItem Bblue;
    private javax.swing.JMenuItem Bcyan;
    private javax.swing.JMenuItem Bgray;
    private javax.swing.JMenuItem Bgreen;
    private javax.swing.JRadioButtonMenuItem Black;
    private javax.swing.JRadioButtonMenuItem Blue;
    private javax.swing.JMenuItem Bmagenta;
    private javax.swing.JMenuItem Bred;
    private javax.swing.JMenuItem Bwhite;
    private javax.swing.JMenuItem Byellow;
    private javax.swing.JRadioButtonMenuItem Cyan;
    private javax.swing.JRadioButtonMenuItem Gray;
    private javax.swing.JRadioButtonMenuItem Green;
    private javax.swing.JRadioButtonMenuItem Magenta;
    private javax.swing.JRadioButtonMenuItem Red;
    private javax.swing.JRadioButtonMenuItem White;
    private javax.swing.JRadioButtonMenuItem Yellow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JCheckBoxMenuItem mnAddLS;
    private javax.swing.JCheckBoxMenuItem mnAddSwB;
    private javax.swing.JMenu mnBackGround;
    private javax.swing.JMenuItem mnClear;
    private javax.swing.JMenuItem mnOval;
    private javax.swing.JMenuItem mnRRect;
    private javax.swing.JMenuItem mnRect;
    private javax.swing.JPanel pnlBackGround;
    // End of variables declaration//GEN-END:variables
}
