/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Nhat Thanh
 */
public class ReplaceForm extends javax.swing.JFrame {

    public JButton getBtnCancel() {
        return btnCancel;
    }
    
    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }
    
    public JButton getBtnReplace() {
        return btnReplace;
    }
    
    public void setBtnReplace(JButton btnReplace) {
        this.btnReplace = btnReplace;
    }
    
    public JButton getBtnReplaceAll() {
        return btnReplaceAll;
    }
    
    public void setBtnReplaceAll(JButton btnReplaceAll) {
        this.btnReplaceAll = btnReplaceAll;
    }
    
    public JTextField getTxtFindWhat() {
        return txtFindWhat;
    }
    
    public void setTxtFindWhat(JTextField txtFindWhat) {
        this.txtFindWhat = txtFindWhat;
    }
    
    public JTextField getTxtReplaceWhat() {
        return txtReplaceWhat;
    }
    
    public void setTxtReplaceWhat(JTextField txtReplaceWhat) {
        this.txtReplaceWhat = txtReplaceWhat;
    }
    
    
    /**
     * Creates new form ReplaceForm
     */
    public ReplaceForm(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    private ReplaceForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFindWhat = new javax.swing.JLabel();
        txtFindWhat = new javax.swing.JTextField();
        btnReplace = new javax.swing.JButton();
        btnReplaceAll = new javax.swing.JButton();
        lblReplace = new javax.swing.JLabel();
        txtReplaceWhat = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFindWhat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblFindWhat.setText("Find What:");

        txtFindWhat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnReplace.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnReplace.setText("Replace");

        btnReplaceAll.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnReplaceAll.setText("Replace All");

        lblReplace.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblReplace.setText("Replace With:");

        txtReplaceWhat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblReplace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtReplaceWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFindWhat)
                        .addGap(39, 39, 39)
                        .addComponent(txtFindWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReplace)
                    .addComponent(btnReplaceAll))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindWhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReplace)
                    .addComponent(lblFindWhat))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReplaceWhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReplaceAll)
                    .addComponent(lblReplace))
                .addGap(40, 40, 40)
                .addComponent(btnCancel)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplaceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReplace;
    private javax.swing.JButton btnReplaceAll;
    private javax.swing.JLabel lblFindWhat;
    private javax.swing.JLabel lblReplace;
    private javax.swing.JTextField txtFindWhat;
    private javax.swing.JTextField txtReplaceWhat;
    // End of variables declaration//GEN-END:variables
}
